/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Preferences.java
 *
 * Created on Feb 22, 2011, 12:02:47 PM
 */

package ngmfconsole;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.beans.PropertyChangeListener;

import javax.swing.JLabel;

/**
 *
 * @author od
 */
public class Preferences extends javax.swing.JPanel {

    public static final String SHOW_HIDDEN = "show_hidden";
    public static final String CLEAR_OUT = "clear_output";

    /** Creates new form Preferences */
    public Preferences(PropertyChangeListener l) {
        initComponents();

        JLabel pref = new JLabel("Preferences");
        pref.setUI(new VerticalLabelUI());
        pref.setHorizontalAlignment(JLabel.CENTER);
        pref.setOpaque(true);
        pref.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        pref.setForeground(Color.WHITE);
        add(pref, BorderLayout.WEST);
        
        addPropertyChangeListener(l);

        jCheckBox1.addItemListener( new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                boolean selected = e.getStateChange() == ItemEvent.SELECTED;
                firePropertyChange(SHOW_HIDDEN, !selected, selected);
            }
        });

        jCheckBox2.addItemListener( new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                boolean selected = e.getStateChange() == ItemEvent.SELECTED;
                firePropertyChange(CLEAR_OUT, !selected, selected);
            }
        });


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setBorder(null);

        jCheckBox1.setText("Show hidden files and folders in dialogs.");

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Always clear output before next run.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(" General ", jPanel1);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
        add(jSeparator1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
